// <auto-generated />
using CodeFirst_Demo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirstDemo.Migrations
{
    [DbContext(typeof(MyDbContext_CodeFirst))]
    partial class MyDbContextCodeFirstModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("CodeFirst_Demo.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 23,
                            Email = "test111@gmail.com.tw",
                            Name = "Roger Lo",
                            Nickname = "",
                            UserName = "友寄隆輝"
                        },
                        new
                        {
                            Id = 2,
                            Age = 24,
                            Email = "test222@gmail.com.tw",
                            Name = "Doraemon",
                            Nickname = "",
                            UserName = "多啦A夢"
                        },
                        new
                        {
                            Id = 3,
                            Age = 25,
                            Email = "test333@gmail.com.tw",
                            Name = "Pikachu",
                            Nickname = "",
                            UserName = "皮卡丘"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
